### ISSUE TITLE
adopt Rigi or similar software for software reverse engineering of Wikia/app

### ISSUE THREAD

**Issue by mixth-sense** [mixth-sense/doom#7]
# Tasks

- [ ] build and run Rigi
- [ ] build and run the associated C code scanner
- [ ] analyse a sample C code
- [ ] create a similar piece of PHP code
- [ ] implement a PHP parser for Rigi

# Links

* [Rigi](https://en.wikipedia.org/wiki/Rigi_%28software%29)
* [Wikia/app](https://github.com/orgs/Wikia/app)

**Comment by macbre** [comment]
Let's include http://www.gupro.de/GXL/tools/tools.html in our list of tools to evaluate. And https://github.com/d3/d3/wiki/Gallery on how to visualize the data we get (e.g. http://www.redotheweb.com/DependencyWheel/)

**Comment by mixth-sense** [comment]
Evaluation of Rigi aborted as not viable. The idea behind the tool is inspiring and worth build upon. As for the tool itself, I could not get it running on a modern 64–bit Linux (14–year–old binary). And I could not build it (15–year–old source) using a typical collection of modern compilers (GCC 4.8).
